Controllers/CaseController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLawFirm.Models;
using System.Data.Entity.Infrastructure;

namespace MvcLawFirm.Controllers
{
    public class CaseController : Controller
    {
        private LawFirmDbContext db = new LawFirmDbContext();

        //
        // GET: /Case/

        public ActionResult Index()
        {
            var nrbm_case = db.NRBM_CASE.Include(n => n.NRBM_CLIENT).Take(20);
            return View(nrbm_case.ToList());
        }
        public ActionResult Results(string searchString)
        {
            string[] search = searchString.Split(null);
            var apt = from m in db.NRBM_CASE
                      where
                      (
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_CLIENT.FNAME)) ||
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_CLIENT.LNAME))
                     )
                      select m;
            return View(apt.ToList());
        }
        //
        // GET: /Case/Details/5

        public ActionResult Details(int id = 0)
        {
            NRBM_CASE nrbm_case = db.NRBM_CASE.Find(id);
            if (nrbm_case == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_case);
        }

        //
        // GET: /Case/Create

        public ActionResult Create()
        {
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName");
            return View();
        }

        //
        // POST: /Case/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NRBM_CASE nrbm_case)
        {
            if (ModelState.IsValid)
            {
                nrbm_case.CASEID = db.NRBM_CASE.Max(x => x.CASEID) + 1;
                db.NRBM_CASE.Add(nrbm_case);
                var odb = ((IObjectContextAdapter)db).ObjectContext;
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateException)
                {
                    odb.Refresh(RefreshMode.ClientWins, nrbm_case);
                }
                return RedirectToAction("Index");
            }
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_case.CLIENTID);
            return View(nrbm_case);
        }

        //
        // GET: /Case/Edit/5

        public ActionResult Edit(int id = 0)
        {
            NRBM_CASE nrbm_case = db.NRBM_CASE.Find(id);
            if (nrbm_case == null)
            {
                return HttpNotFound();
            }
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_case.CLIENTID);
            return View(nrbm_case);
        }

        //
        // POST: /Case/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NRBM_CASE nrbm_case)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nrbm_case).State = EntityState.Modified;
                var odb = ((IObjectContextAdapter)db).ObjectContext;
                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    odb.Refresh(RefreshMode.StoreWins, nrbm_case);
                }
                return RedirectToAction("Index");
            }
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_case.CLIENTID);
            return View(nrbm_case);
        }

        //
        // GET: /Case/Delete/5

        public ActionResult Delete(int id = 0)
        {
            NRBM_CASE nrbm_case = db.NRBM_CASE.Find(id);
            if (nrbm_case == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_case);
        }

        //
        // POST: /Case/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NRBM_CASE nrbm_case = db.NRBM_CASE.Find(id);
            db.NRBM_CASE.Remove(nrbm_case);
            var odb = ((IObjectContextAdapter)db).ObjectContext;
            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                odb.Refresh(RefreshMode.StoreWins, nrbm_case);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Case/Create.cshtml
@model MvcLawFirm.Models.NRBM_CASE

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Case</legend>
<<<<<<< HEAD
       
=======
>>>>>>> 91612003e271f7d38928ad08d88dc13fdb8742dd

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENTID, "Client")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CLIENTID", String.Empty) @Html.ActionLink("Create New Client", "../Client/Create")
            @Html.ValidationMessageFor(model => model.CLIENTID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SDATE, "Start Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EDATE, "End Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EVIDENCE, "Evidence")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EVIDENCE)
            @Html.ValidationMessageFor(model => model.EVIDENCE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CATEGORY, "Category")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CATEGORY)
            @Html.ValidationMessageFor(model => model.CATEGORY)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LITIGATION, "Litigation")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LITIGATION)
            @Html.ValidationMessageFor(model => model.LITIGATION)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NOTES, "Notes")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NOTES)
            @Html.ValidationMessageFor(model => model.NOTES)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}


Views/Case/Delete.cshtml
@model MvcLawFirm.Models.NRBM_CASE

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Case</h2>

<h3>Are you sure you want to delete this?</h3>
<table>
    <tr>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Evidence
        </th>
        <th>
            Category
        </th>
        <th>
            Litigation
        </th>
        <th>
            Notes
        </th>
        <th></th>
    </tr>

    <tr>
        <td>           
            @Html.DisplayFor(model => model.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(model => model.SDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.EDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.EVIDENCE)
        </td>
        <td>
            @Html.DisplayFor(model => model.CATEGORY)
        </td>
        <td>
            @Html.DisplayFor(model => model.LITIGATION)
        </td>
        <td>
            @Html.DisplayFor(model => model.NOTES)
        </td>
        <td>
            @using (Html.BeginForm()){
            @Html.AntiForgeryToken()
            <p>
                 <input type="submit" value="Delete" /> |
                 @Html.ActionLink("Back to List", "Index")
            </p>
            }
        </td>
    </tr>

</table>

Views/Case/Details.cshtml
@model MvcLawFirm.Models.NRBM_CASE

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Case</legend>


    <div class="display-label">
         Client
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NRBM_CLIENT.FullName)
    </div>

    <div class="display-label">
         Start Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SDATE)
    </div>

    <div class="display-label">
         End Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EDATE)
    </div>

    <div class="display-label">
         Evidence
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EVIDENCE)
    </div>

    <div class="display-label">
         Category
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.CATEGORY)
    </div>

    <div class="display-label">
         Litigation
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LITIGATION)
    </div>

    <div class="display-label">
         Notes
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NOTES)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.CASEID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Case/Edit.cshtml
@model MvcLawFirm.Models.NRBM_CASE

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    <fieldset>
        <legend>Case</legend>
        @Html.HiddenFor(model=> model.CASEID)
        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENTID, "Client")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CLIENTID", String.Empty)
            @Html.ValidationMessageFor(model => model.CLIENTID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SDATE, "Start Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EDATE, "End Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EVIDENCE, "Evidence")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EVIDENCE)
            @Html.ValidationMessageFor(model => model.EVIDENCE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CATEGORY, "Category")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CATEGORY)
            @Html.ValidationMessageFor(model => model.CATEGORY)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LITIGATION, "Litigation")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LITIGATION)
            @Html.ValidationMessageFor(model => model.LITIGATION)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NOTES, "Notes")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NOTES)
            @Html.ValidationMessageFor(model => model.NOTES)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}

Views/Case/Index.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_CASE>

@{
    ViewBag.Title = "Index";
}

<h2>Cases</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
     @using (Html.BeginForm("Results", "Case")){    
         <p> Search: @Html.TextBox("SearchString") <br />   
         <input type="submit" value="Filter" /></p> 
     } 
<table>
    <tr>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Evidence
        </th>
        <th>
            Category
        </th>
        <th>
            Litigation
        </th>
        <th>
            Notes
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>           
             @Html.DisplayFor(modelItem => item.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EVIDENCE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LITIGATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NOTES)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CASEID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CASEID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CASEID })
        </td>
    </tr>
}

</table>

Views/Case/Results.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_CASE>

@{
    ViewBag.Title = "Results";
}

<h2>Case Search Results</h2>

<p>
    @Html.ActionLink("Create New", "Create") 
</p>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<table>
    <tr>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Evidence
        </th>
        <th>
            Category
        </th>
        <th>
            Litigation
        </th>
        <th>
            Notes
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>           
             @Html.DisplayFor(modelItem => item.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EVIDENCE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CATEGORY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LITIGATION)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NOTES)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CASEID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CASEID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CASEID })
        </td>
    </tr>
}

</table>