Controllers/CounselsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLawFirm.Models;

namespace MvcLawFirm.Controllers
{
    public class CounselsController : Controller
    {
        private LawFirmDbContext db = new LawFirmDbContext();

        //
        // GET: /Counsels/

        public ActionResult Index()
        {
            var nrbm_counsels = db.NRBM_COUNSELS.Include(n => n.NRBM_CLIENT).Include(n => n.NRBM_LAWYER).Take(20);
            return View(nrbm_counsels.ToList());
        }
        public ActionResult Results(string searchString)
        {
            string[] search = searchString.Split(null);
            var apt = from m in db.NRBM_COUNSELS
                      where
                     (
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_LAWYER.FNAME)) ||
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_LAWYER.LNAME))
                     )
                     ||
                     (
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_CLIENT.FNAME)) ||
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_CLIENT.LNAME))
                     )
                      select m;
            return View(apt.ToList());
        }
        //
        // GET: /Counsels2/Details/5

        public ActionResult Details(int id = 0)
        {
            NRBM_COUNSELS nrbm_counsels = db.NRBM_COUNSELS.Find(id);
            if (nrbm_counsels == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_counsels);
        }

        //
        // GET: /Counsels2/Create

        public ActionResult Create()
        {
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName");
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName");
            return View();
        }

        //
        // POST: /Counsels2/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NRBM_COUNSELS nrbm_counsels)
        {
            if (ModelState.IsValid)
            {
                db.NRBM_COUNSELS.Add(nrbm_counsels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_counsels.CLIENTID);
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_counsels.LAWID);
            return View(nrbm_counsels);
        }

        //
        // GET: /Counsels2/Edit/5

        public ActionResult Edit(int id = 0)
        {
            NRBM_COUNSELS nrbm_counsels = db.NRBM_COUNSELS.Find(id);
            if (nrbm_counsels == null)
            {
                return HttpNotFound();
            }
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_counsels.CLIENTID);
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_counsels.LAWID);
            return View(nrbm_counsels);
        }

        //
        // POST: /Counsels2/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NRBM_COUNSELS nrbm_counsels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nrbm_counsels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CLIENTID = new SelectList(db.NRBM_CLIENT, "CLIENTID", "FullName", nrbm_counsels.CLIENTID);
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_counsels.LAWID);
            return View(nrbm_counsels);
        }

        //
        // GET: /Counsels2/Delete/5

        public ActionResult Delete(int id = 0)
        {
            NRBM_COUNSELS nrbm_counsels = db.NRBM_COUNSELS.Find(id);
            if (nrbm_counsels == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_counsels);
        }

        //
        // POST: /Counsels2/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NRBM_COUNSELS nrbm_counsels = db.NRBM_COUNSELS.Find(id);
            db.NRBM_COUNSELS.Remove(nrbm_counsels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Counsels/Create.cshtml
@model MvcLawFirm.Models.NRBM_COUNSELS

@{
    ViewBag.Title = "Create";
}

<h2>Create a Counsel Relation</h2>

@using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    <fieldset>
        <legend>Counsels</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.LAWID, "Lawyer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LAWID", String.Empty) @Html.ActionLink("Create New Lawyer", "../Lawyer/Create")
            @Html.ValidationMessageFor(model => model.LAWID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENTID, "Client")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CLIENTID", String.Empty) @Html.ActionLink("Create New Client", "../Client/Create")
            @Html.ValidationMessageFor(model => model.CLIENTID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.SDATE, "Start Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.EDATE, "End Date")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HOURS, "Hours")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HOURS)
            @Html.ValidationMessageFor(model => model.HOURS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FEES, "Fees")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FEES)
            @Html.ValidationMessageFor(model => model.FEES)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}

Views/Counsels/Delete.cshtml
@model MvcLawFirm.Models.NRBM_COUNSELS

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Counsels Relation</h2>

<h3>Are you sure you want to delete this?</h3>
<table>
    <tr>
        <th>
            Lawyer
        </th>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Hours
        </th>
        <th>
            Fees
        </th>
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(model => model.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(model => model.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(model => model.SDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.EDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.HOURS)
        </td>
        <td>
            @Html.DisplayFor(model => model.FEES)
        </td>
        <td>
            @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
             <p>
                 <input type="submit" value="Delete" /> |
                 @Html.ActionLink("Back to List", "Index")
             </p>
            }
        </td>
    </tr>

</table>

Views/Counsels/Details.cshtml
@model MvcLawFirm.Models.NRBM_COUNSELS

@{
    ViewBag.Title = "Details";
}

<h2>Counsels Relation Details</h2>

<fieldset>
    <legend>COUNSELS</legend>

    <div class="display-label">
         Lawyer
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NRBM_LAWYER.FullName)
    </div>

    <div class="display-label">
         Client
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NRBM_CLIENT.FullName)
    </div>

    <div class="editor-label">
        Start Date
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.SDATE)
    </div>

    <div class="editor-label">
        End Date
    </div>
    <div class="editor-field">
        @Html.DisplayFor(model => model.EDATE)
    </div>

    <div class="display-label">
         Hours
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HOURS)
    </div>

    <div class="display-label">
         Fees
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.FEES)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.COUNSELSID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Counsels/Edit.cshtml
@model MvcLawFirm.Models.NRBM_COUNSELS

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Counsels Relation</h2>

@using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

    <fieldset>
        <legend>Counsels</legend>
        @Html.HiddenFor(model=> model.COUNSELSID)
        <div class="editor-label">
            @Html.LabelFor(model => model.LAWID, "Lawyer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LAWID", String.Empty)
            @Html.ValidationMessageFor(model => model.LAWID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.CLIENTID, "Client")
        </div>
        <div class="editor-field">
            @Html.DropDownList("CLIENTID", String.Empty)
            @Html.ValidationMessageFor(model => model.CLIENTID)
        </div>

        <div class="editor-label">
            <label for="SDATE">Start Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            <label for="EDATE">End Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.HOURS, "Hours")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HOURS)
            @Html.ValidationMessageFor(model => model.HOURS)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.FEES, "Fees")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FEES)
            @Html.ValidationMessageFor(model => model.FEES)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}

Views/Counsels/Index.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_COUNSELS>

@{
    ViewBag.Title = "Index";
}

<h2>Counsels</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
     @using (Html.BeginForm("Results", "Counsels")){    
         <p> Search: @Html.TextBox("SearchString") <br />   
         <input type="submit" value="Filter" /></p> 
     }
<table>
    <tr>
        <th>
            Lawyer
        </th>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EDATE)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.COUNSELSID }) |
            @Html.ActionLink("Details", "Details", new { id=item.COUNSELSID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.COUNSELSID })
        </td>
    </tr>
}

</table>

Views/Counsels/Results.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_COUNSELS>

@{
    ViewBag.Title = "Results";
}

<h2>Counsel Search Results</h2>

<p>
    @Html.ActionLink("Create New", "Create") 
</p>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

<table>
    <tr>
        <th>
            Lawyer
        </th>
        <th>
            Client
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Hours
        </th>
        <td>
            Fees
        </td>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_CLIENT.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HOURS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FEES)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.COUNSELSID }) |
            @Html.ActionLink("Details", "Details", new { id=item.COUNSELSID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.COUNSELSID })
        </td>
    </tr>
}

</table>