Controllers/WorkController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLawFirm.Models;

namespace MvcLawFirm.Controllers
{
    public class WorkController : Controller
    {
        private LawFirmDbContext db = new LawFirmDbContext();

        //
        // GET: /Work/

        public ActionResult Index()
        {
            var nrbm_worksfor = db.NRBM_WORKSFOR.Include(n => n.NRBM_LAWYER).Include(n => n.NRBM_STAFF).Take(20);
            return View(nrbm_worksfor.ToList());
        }
        public ActionResult Results(string searchString)
        {
            string[] search = searchString.Split(null);
            var apt = from m in db.NRBM_WORKSFOR
                      where
                     (
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_LAWYER.FNAME)) ||
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_LAWYER.LNAME))
                     )
                     ||
                     (
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_STAFF.FNAME)) ||
                        (string.IsNullOrEmpty(searchString) ? true : search.Contains(m.NRBM_STAFF.LNAME))
                     )
                      select m;
            return View(apt.ToList());
        }
        //
        // GET: /Work/Details/5

        public ActionResult Details(int id = 0)
        {
            NRBM_WORKSFOR nrbm_worksfor = db.NRBM_WORKSFOR.Find(id);
            if (nrbm_worksfor == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_worksfor);
        }

        //
        // GET: /Work/Create

        public ActionResult Create()
        {
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName");
            ViewBag.STAFFID = new SelectList(db.NRBM_STAFF, "STAFFID", "FullName");
            return View();
        }

        //
        // POST: /Work/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(NRBM_WORKSFOR nrbm_worksfor)
        {
            if (ModelState.IsValid)
            {
                db.NRBM_WORKSFOR.Add(nrbm_worksfor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_worksfor.LAWID);
            ViewBag.STAFFID = new SelectList(db.NRBM_STAFF, "STAFFID", "FullName", nrbm_worksfor.STAFFID);
            return View(nrbm_worksfor);
        }

        //
        // GET: /Work/Edit/5

        public ActionResult Edit(int id = 0)
        {
            NRBM_WORKSFOR nrbm_worksfor = db.NRBM_WORKSFOR.Find(id);
            if (nrbm_worksfor == null)
            {
                return HttpNotFound();
            }
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_worksfor.LAWID);
            ViewBag.STAFFID = new SelectList(db.NRBM_STAFF, "STAFFID", "FullName", nrbm_worksfor.STAFFID);
            return View(nrbm_worksfor);
        }

        //
        // POST: /Work/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(NRBM_WORKSFOR nrbm_worksfor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nrbm_worksfor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LAWID = new SelectList(db.NRBM_LAWYER, "LAWID", "FullName", nrbm_worksfor.LAWID);
            ViewBag.STAFFID = new SelectList(db.NRBM_STAFF, "STAFFID", "FullName", nrbm_worksfor.STAFFID);
            return View(nrbm_worksfor);
        }

        //
        // GET: /Work/Delete/5

        public ActionResult Delete(int id = 0)
        {
            NRBM_WORKSFOR nrbm_worksfor = db.NRBM_WORKSFOR.Find(id);
            if (nrbm_worksfor == null)
            {
                return HttpNotFound();
            }
            return View(nrbm_worksfor);
        }

        //
        // POST: /Work/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NRBM_WORKSFOR nrbm_worksfor = db.NRBM_WORKSFOR.Find(id);
            db.NRBM_WORKSFOR.Remove(nrbm_worksfor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Views/Work/Create.cshtml
@model MvcLawFirm.Models.NRBM_WORKSFOR

@{
    ViewBag.Title = "Create";
}

<h2>Create Works</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WORK</legend>
        <div class="editor-label">
            @Html.LabelFor(model => model.STAFFID, "Staff")
        </div>
        <div class="editor-field">
            @Html.DropDownList("STAFFID", String.Empty) @Html.ActionLink("Create New Staff Member", "../Staff/Create")
            @Html.ValidationMessageFor(model => model.STAFFID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LAWID, "Lawyer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LAWID", String.Empty) @Html.ActionLink("Create New Lawyer", "../Lawyer/Create")
            @Html.ValidationMessageFor(model => model.LAWID)
        </div>

        <div class="editor-label">
            <label for="SDATE">Start Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            <label for="EDATE">End Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            Salary
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SALARY)
            @Html.ValidationMessageFor(model => model.SALARY)
        </div>

        <div class="editor-label">
            Hours
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HOURS)
            @Html.ValidationMessageFor(model => model.HOURS)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}

Views/Work/Delete.cshtml
@model MvcLawFirm.Models.NRBM_WORKSFOR

@{
    ViewBag.Title = "Delete";
}

<h2>Delete Works For Relation</h2>

<h3>Are you sure you want to delete this?</h3>
<table>
    <tr>
        <th>
            Staff
        </th>
        <th>
            Lawyer
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Salary
        </th>
        <th>
            Hours
        </th>
        <th></th>
    </tr>

    <tr>
        <td>
            @Html.DisplayFor(model => model.NRBM_STAFF.FullName)
        </td>
        <td>
            @Html.DisplayFor(model => model.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(model => model.SDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.EDATE)
        </td>
        <td>
            @Html.DisplayFor(model => model.SALARY)
        </td>
        <td>
            @Html.DisplayFor(model => model.HOURS)
        </td>
        <td>
        @using (Html.BeginForm()) {
         @Html.AntiForgeryToken()
         <p>
              <input type="submit" value="Delete" /> |
              @Html.ActionLink("Back to List", "Index")
         </p>
        }
        </td>
    </tr>

</table>

Views/Work/Details.cshtml
@model MvcLawFirm.Models.NRBM_WORKSFOR

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>WORK</legend>

    <div class="display-label">
         Staff
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NRBM_STAFF.FullName)
    </div>

    <div class="display-label">
         Lawyer
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NRBM_LAWYER.FullName)
    </div>

    <div class="display-label">
         Start Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SDATE)
    </div>

    <div class="display-label">
         End Date
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.EDATE)
    </div>

    <div class="display-label">
         Salary
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.SALARY)
    </div>

    <div class="display-label">
         Hours
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.HOURS)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.WORKID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Work/Edit.cshtml
@model MvcLawFirm.Models.NRBM_WORKSFOR

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Payroll</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>WORK</legend>
        @Html.HiddenFor(model=>model.WORKID)
        <div class="editor-label">
            @Html.LabelFor(model => model.STAFFID, "Staff")
        </div>
        <div class="editor-field">
            @Html.DropDownList("STAFFID", String.Empty)
            @Html.ValidationMessageFor(model => model.STAFFID)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LAWID, "Lawyer")
        </div>
        <div class="editor-field">
            @Html.DropDownList("LAWID", String.Empty)
            @Html.ValidationMessageFor(model => model.LAWID)
        </div>

        <div class="editor-label">
            <label for="SDATE">Start Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SDATE)
            @Html.ValidationMessageFor(model => model.SDATE)
        </div>

        <div class="editor-label">
            <label for="EDATE">End Date</label>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.EDATE)
            @Html.ValidationMessageFor(model => model.EDATE)
        </div>

        <div class="editor-label">
            Salary
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SALARY)
            @Html.ValidationMessageFor(model => model.SALARY)
        </div>

        <div class="editor-label">
            Hours
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.HOURS)
            @Html.ValidationMessageFor(model => model.HOURS)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/jquery.ui.core.min.js", "~/Scripts/jquery.ui.datepicker.min.js", "~/Scripts/DatePickerReady.js")
    @Styles.Render("~/Content/themes/base/jquery.ui.core.css", "~/Content/themes/base/jquery.ui.datepicker.css", "~/Content/themes/base/jquery.ui.theme.css")
}

Views/Work/Index.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_WORKSFOR>

@{
    ViewBag.Title = "Index";
}

<h2>Payroll</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
     @using (Html.BeginForm("Results", "Work")){    
         <p> Search: @Html.TextBox("SearchString") <br />   
         <input type="submit" value="Filter" /></p> 
     }
<table>
    <tr>
        <th>
            Staff
        </th>
        <th>
            Lawyer
        </th>
        <th>
            Salary
        </th>
        <th>
            Hours
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_STAFF.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SALARY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HOURS)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WORKID }) |
            @Html.ActionLink("Details", "Details", new { id=item.WORKID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WORKID })
        </td>
    </tr>
}

</table>

Views/Work/Results.cshtml
@model IEnumerable<MvcLawFirm.Models.NRBM_WORKSFOR>

@{
    ViewBag.Title = "Results";
}

<h2>Works For Search Results</h2>

<p>
    @Html.ActionLink("Create New", "Create") 
</p>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<table>
    <tr>
        <th>
            Staff
        </th>
        <th>
            Lawyer
        </th>
        <th>
            Start Date
        </th>
        <th>
            End Date
        </th>
        <th>
            Salary
        </th>
        <th>
            Hours
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_STAFF.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NRBM_LAWYER.FullName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EDATE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SALARY)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.HOURS)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.WORKID }) |
            @Html.ActionLink("Details", "Details", new { id=item.WORKID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.WORKID })
        </td>
    </tr>
}

</table>